# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('Materiel', 'Matériel pédagogique'), ('Entretien', 'Entretien'), ('Logistique', 'Logistique'), ('Activites', 'Activités extrascolaires'), ('Autres', 'Autres dépenses')], max_length=50)),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('responsable_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(default='Validée', max_length=20)),
                ('responsable_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
