# Generated by Django 5.2.8 on 2026-01-05 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('Materiel', 'Matériel pédagogique'), ('Entretien', 'Entretien'), ('Logistique', 'Logistique'), ('Activites', 'Activités extrascolaires'), ('Autres', 'Autres dépenses')], max_length=50)),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=100)),
                ('statut', models.CharField(default='Validée', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RecuFacture',
        ),
    ]
