# Generated by Django 5.2.8 on 2026-01-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('depenses', '0002_depense_delete_recufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='responsable',
        ),
        migrations.AddField(
            model_name='depense',
            name='responsable_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='depense',
            name='responsable_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
