# Generated by Django 5.2.8 on 2026-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_remove_depense_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/'),
        ),
    ]
