# Generated by Django 5.2.8 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='can_manage_etudiants',
            field=models.CharField(choices=[('none', 'Aucun'), ('lecture', 'Lecture'), ('ecriture', 'Écriture')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_finance',
            field=models.CharField(choices=[('none', 'Aucun'), ('lecture', 'Lecture'), ('ecriture', 'Écriture')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_logistique',
            field=models.CharField(choices=[('none', 'Aucun'), ('lecture', 'Lecture'), ('ecriture', 'Écriture')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_pedagogie',
            field=models.CharField(choices=[('none', 'Aucun'), ('lecture', 'Lecture'), ('ecriture', 'Écriture')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_rh',
            field=models.CharField(choices=[('none', 'Aucun'), ('lecture', 'Lecture'), ('ecriture', 'Écriture')], default='none', max_length=10),
        ),
    ]
