# Generated by Django 6.0.2 on 2026-02-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('can_manage_rh', models.BooleanField(default=False)),
                ('can_manage_pedagogie', models.BooleanField(default=False)),
                ('can_manage_logistique', models.BooleanField(default=False)),
                ('can_manage_finance', models.BooleanField(default=False)),
                ('can_manage_etudiants', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='responsableRh', max_length=50),
        ),
    ]
