# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssiduiteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard')], max_length=10)),
                ('minutes_retard', models.PositiveIntegerField(blank=True, null=True)),
                ('justifie', models.BooleanField(default=False)),
                ('justificatif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assiduite', to='etudiants.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assiduite', to='modules.module')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
