# Generated by Django 6.0.2 on 2026-02-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0007_inscription_niveau_alter_inscription_unique_together'),
        ('modules', '0003_module_coefficient_module_has_tp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssiduiteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard')], max_length=10)),
                ('minutes_retard', models.PositiveIntegerField(blank=True, null=True)),
                ('justifie', models.BooleanField(default=False)),
                ('justificatif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assiduite', to='etudiants.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assiduite', to='modules.module')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
