# Generated by Django 4.2.30 on 2026-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assiduite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assiduiterecord',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='assiduite/justificatifs/'),
        ),
    ]
