# Generated by Django 5.2.8 on 2026-01-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formateurs.formateur')),
            ],
        ),
    ]
