# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('duree', models.PositiveIntegerField(default=0, help_text='Durée en heures')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coefficient du module')),
                ('has_tp', models.BooleanField(default=False, help_text='Le module comporte-t-il un TP ?')),
                ('pourcentage_cc', models.PositiveIntegerField(default=30, help_text='Pourcentage CC (0-100)')),
                ('pourcentage_sn', models.PositiveIntegerField(default=70, help_text='Pourcentage SN (0-100)')),
                ('pourcentage_tp', models.PositiveIntegerField(default=0, help_text='Pourcentage TP (0-100, si has_tp)')),
                ('semestre', models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], default='Semestre 1', help_text='Semestre auquel appartient le cours', max_length=20)),
            ],
        ),
    ]
