# Generated by Django 5.2.8 on 2026-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='formateur',
        ),
        migrations.AddField(
            model_name='module',
            name='duree',
            field=models.PositiveIntegerField(default=0, help_text='Durée en heures'),
        ),
    ]
