# Generated by Django 4.2.30 on 2026-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='has_tp',
        ),
        migrations.RemoveField(
            model_name='module',
            name='pourcentage_cc',
        ),
        migrations.RemoveField(
            model_name='module',
            name='pourcentage_sn',
        ),
        migrations.RemoveField(
            model_name='module',
            name='pourcentage_tp',
        ),
    ]
