# Generated by Django 6.0.2 on 2026-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_formateur_module_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Coefficient du module'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_tp',
            field=models.BooleanField(default=False, help_text='Le module comporte-t-il un TP ?'),
        ),
        migrations.AddField(
            model_name='module',
            name='pourcentage_cc',
            field=models.PositiveIntegerField(default=30, help_text='Pourcentage CC (0-100)'),
        ),
        migrations.AddField(
            model_name='module',
            name='pourcentage_sn',
            field=models.PositiveIntegerField(default=70, help_text='Pourcentage SN (0-100)'),
        ),
        migrations.AddField(
            model_name='module',
            name='pourcentage_tp',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage TP (0-100, si has_tp)'),
        ),
    ]
