# Generated by Django 5.2.8 on 2026-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code_ue',
            field=models.CharField(blank=True, default='', help_text='Code UE (ex: UE101)', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de crédits ECTS'),
        ),
    ]
