# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilierePaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_installments_enabled', models.BooleanField(default=False)),
                ('monthly_enabled', models.BooleanField(default=False)),
                ('monthly_start_date', models.DateField(blank=True, null=True)),
                ('monthly_due_day', models.PositiveSmallIntegerField(default=28)),
                ('monthly_installments_count', models.PositiveSmallIntegerField(default=4)),
                ('alert_days_before', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_policy', to='academique.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligatoire', models.BooleanField(default=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academique.classe')),
            ],
            options={
                'ordering': ['classe__nom', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FOUR_INSTALLMENTS', '04 tranches'), ('MONTHLY', 'Mensuel')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_start_date', models.DateField(blank=True, null=True)),
                ('monthly_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alert_days_before', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='etudiants.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_plans', to='academique.filiere')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_plans', to='paiements.filierepaymentpolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiellement payée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='paiements.studentpaymentplan')),
            ],
            options={
                'ordering': ['due_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiement_type', models.CharField(choices=[('FORMATION', 'Frais de formation'), ('INSCRIPTION', "Frais d'inscription")], default='FORMATION', help_text="Type de paiement pour distinguer frais de formation et frais d'inscription", max_length=20)),
                ('montant_du', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_restant', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=50, null=True)),
                ('justificatif', models.FileField(blank=True, help_text='Importer une photo ou un PDF comme preuve du paiement', null=True, upload_to='paiements/justificatifs/')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='etudiants.etudiant')),
                ('filiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='academique.filiere')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='paiements.frais')),
            ],
        ),
        migrations.CreateModel(
            name='FiliereInstallmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='four_installments', to='paiements.filierepaymentpolicy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentpaymentplan',
            constraint=models.UniqueConstraint(fields=('etudiant', 'filiere'), name='unique_student_plan_per_filiere'),
        ),
        migrations.AddConstraint(
            model_name='studentpaymentinstallment',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_student_installment_order'),
        ),
        migrations.AddConstraint(
            model_name='frais',
            constraint=models.UniqueConstraint(fields=('classe', 'libelle'), name='unique_frais_per_class_label'),
        ),
        migrations.AddConstraint(
            model_name='filiereinstallmenttemplate',
            constraint=models.UniqueConstraint(fields=('policy', 'order'), name='unique_installment_template_order'),
        ),
    ]
