# Generated by Django 5.2.8 on 2025-12-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=255)),
                ('formation', models.CharField(max_length=255)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_restant', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
