# Generated by Django 5.2.8 on 2026-01-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('formations', '0002_remove_formation_description_formation_montant'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='noms',
        ),
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='etudiants.etudiant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='formations.formation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_du',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
