# Generated by Django 5.2.8 on 2026-07-17 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0013_backfill_preinscription_annee_academique'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentplan',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_plans', to='academique.classe'),
        ),
        migrations.AddField(
            model_name='studentpaymentplan',
            name='is_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentpaymentplan',
            name='mode',
            field=models.CharField(choices=[('FOUR_INSTALLMENTS', '04 tranches'), ('MONTHLY', 'Mensuel'), ('CUSTOM', 'Personnalisé')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClassePaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_days_before', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='academique.classe')),
            ],
            options={
                'ordering': ['classe__nom'],
            },
        ),
        migrations.CreateModel(
            name='ClassePaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='paiements.classepaymentschedule')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'order'), name='unique_classe_installment_order')],
            },
        ),
    ]
