# Generated by Django 5.2.8 on 2026-01-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_remove_formation_description_formation_montant'),
        ('paiements', '0002_remove_paiement_noms_paiement_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='formation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='formations.formation'),
        ),
    ]
