# Generated by Django 5.2.8 on 2026-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_paiement_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='justificatif',
            field=models.FileField(blank=True, help_text='Importer une photo ou un PDF comme preuve du paiement', null=True, upload_to='paiements/justificatifs/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=50, null=True),
        ),
    ]
