# Generated by Django 5.2.8 on 2026-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_paiement_justificatif_paiement_moyen_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant_du',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='solde_restant',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
