# Generated by Django 6.0.2 on 2026-04-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('paiements', '0005_alter_paiement_montant_du_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligatoire', models.BooleanField(default=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academique.classe')),
            ],
            options={
                'ordering': ['classe__nom', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='paiements.frais'),
        ),
        migrations.AddConstraint(
            model_name='frais',
            constraint=models.UniqueConstraint(fields=('classe', 'libelle'), name='unique_frais_per_class_label'),
        ),
    ]
