# Generated by Django 6.0.2 on 2026-04-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0009_inscription_annee_academique_ref_inscription_classe_and_more'),
        ('formations', '0006_add_frais_inscription'),
        ('paiements', '0007_add_paiement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire'), ('cheque', 'Cheque')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FormationPaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('four_installments_enabled', models.BooleanField(default=False)),
                ('monthly_enabled', models.BooleanField(default=False)),
                ('monthly_start_date', models.DateField(blank=True, null=True)),
                ('monthly_due_day', models.PositiveSmallIntegerField(default=28)),
                ('monthly_installments_count', models.PositiveSmallIntegerField(default=4)),
                ('alert_days_before', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_policy', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FOUR_INSTALLMENTS', '04 tranches'), ('MONTHLY', 'Mensuel')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_start_date', models.DateField(blank=True, null=True)),
                ('monthly_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alert_days_before', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='etudiants.etudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_plans', to='formations.formation')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_plans', to='paiements.formationpaymentpolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiellement payee'), ('PAID', 'Payee'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='paiements.studentpaymentplan')),
            ],
            options={
                'ordering': ['due_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormationInstallmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='four_installments', to='paiements.formationpaymentpolicy')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'order'), name='unique_installment_template_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentpaymentplan',
            constraint=models.UniqueConstraint(fields=('etudiant', 'formation'), name='unique_student_plan_per_formation'),
        ),
        migrations.AddConstraint(
            model_name='studentpaymentinstallment',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_student_installment_order'),
        ),
    ]
