# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('article', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('Informatique', 'Informatique'), ('Mobilier', 'Mobilier'), ('Électronique', 'Électronique'), ('Papeterie', 'Papeterie'), ('Autre', 'Autre')], max_length=100)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupee', 'Occupee'), ('En panne', 'En panne')], default='Disponible', max_length=20)),
            ],
        ),
    ]
