# Generated by Django 5.2.8 on 2026-06-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('categorie', models.CharField(choices=[('Informatique', 'Informatique'), ('Mobilier', 'Mobilier'), ('Électronique', 'Électronique'), ('Papeterie', 'Papeterie'), ('Fourniture', 'Fourniture'), ('Équipement', 'Équipement'), ('Autre', 'Autre')], default='Autre', max_length=100)),
                ('quantite_totale', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('article', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('Informatique', 'Informatique'), ('Mobilier', 'Mobilier'), ('Électronique', 'Électronique'), ('Papeterie', 'Papeterie'), ('Autre', 'Autre')], max_length=100)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupee', 'Occupee'), ('En panne', 'En panne')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('en_utilisation', 'En utilisation'), ('en_panne', 'En panne'), ('en_maintenance', 'En maintenance'), ('reforme', 'Réformé')], default='en_stock', max_length=20)),
                ('condition', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('usage', 'Usagé'), ('endommage', 'Endommagé')], default='neuf', max_length=20)),
                ('localisation', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('attributaire_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='inventaires.article')),
                ('attributaire_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée en stock'), ('sortie', 'Sortie / Attribution'), ('retour', 'Retour en stock'), ('transfert', 'Transfert'), ('maintenance', 'Envoi en maintenance'), ('reforme', 'Réforme')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('responsable_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destinataire_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('localisation_source', models.CharField(blank=True, default='', max_length=200)),
                ('localisation_destination', models.CharField(blank=True, default='', max_length=200)),
                ('destinataire_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_recus', to='contenttypes.contenttype')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaires.exemplaire')),
                ('responsable_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
