# Generated by Django 5.2.8 on 2025-12-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventaire',
            old_name='nom',
            new_name='article',
        ),
    ]
