# Generated by Django 5.2.8 on 2025-12-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0002_rename_nom_inventaire_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventaire',
            options={},
        ),
    ]
