# Generated by Django 5.2.8 on 2025-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0003_alter_inventaire_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('en_panne', 'En panne')], max_length=20),
        ),
    ]
