# Generated by Django 5.2.8 on 2025-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0004_alter_article_options_alter_article_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
