# Generated by Django 5.2.8 on 2025-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0005_inventaire_reference_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
