# Generated by Django 5.2.8 on 2025-12-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0006_inventaire_statut_alter_inventaire_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Occupée', 'Occupée'), ('En panne', 'En panne')], default='Disponible', max_length=20),
        ),
    ]
