# Generated by Django 5.2.8 on 2025-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0007_alter_inventaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(default='Disponible', max_length=20),
        ),
    ]
