# Generated by Django 5.2.8 on 2026-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0008_alter_inventaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='categorie',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Mobilier', 'Mobilier'), ('Électronique', 'Électronique'), ('Papeterie', 'Papeterie'), ('Autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible'), ('Réservé', 'Réservé')], default='Disponible', max_length=20),
        ),
    ]
