# Generated by Django 5.2.8 on 2026-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0009_alter_inventaire_categorie_alter_inventaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='reference',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Occupee', 'Occupee'), ('En panne', 'En panne')], default='Disponible', max_length=20),
        ),
    ]
