# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('salaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('specialites', models.ManyToManyField(related_name='formateurs', to='modules.module')),
            ],
        ),
    ]
