# Generated by Django 5.2.8 on 2026-06-30 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0002_formateur_type_and_taux_horaire'),
        ('modules', '0003_module_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CoursDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('fichier', models.FileField(upload_to='cours/documents/')),
                ('est_visible_etudiants', models.BooleanField(default=False)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_documents', to='formateurs.formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_documents', to='modules.module')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
    ]
