# Generated by Django 5.2.8 on 2026-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0002_initial'),
        ('modules', '0002_remove_module_formateur_module_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='specialite',
        ),
        migrations.AddField(
            model_name='formateur',
            name='specialites',
            field=models.ManyToManyField(related_name='formateurs', to='modules.module'),
        ),
    ]
