# Generated by Django 5.2.8 on 2026-01-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0003_remove_formateur_specialite_formateur_specialites'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
