# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('modules', '0001_initial'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], max_length=20)),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9)),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, help_text='Note CC sur 20', max_digits=5, null=True)),
                ('note_sn', models.DecimalField(blank=True, decimal_places=2, help_text='Note SN sur 20', max_digits=5, null=True)),
                ('note_tp', models.DecimalField(blank=True, decimal_places=2, help_text='Note TP sur 20 (si applicable)', max_digits=5, null=True)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, help_text='Note Rattrapage sur 20 (facultatif)', max_digits=5, null=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, help_text='Note finale sur 20', max_digits=5, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academique.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academique.evaluation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.module')),
            ],
        ),
    ]
