# Generated by Django 5.2.8 on 2026-01-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0002_etudiantdocument'),
        ('modules', '0002_remove_module_formateur_module_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], max_length=20)),
                ('note_cc', models.DecimalField(blank=True, decimal_places=2, help_text='Note CC sur 30', max_digits=5, null=True)),
                ('note_sn', models.DecimalField(blank=True, decimal_places=2, help_text='Note SN sur 70', max_digits=5, null=True)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, help_text='Note Rattrapage sur 70 (facultatif)', max_digits=5, null=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, help_text='Note finale sur 100', max_digits=5, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.module')),
            ],
        ),
    ]
