# Generated by Django 4.2.30 on 2026-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_tp',
        ),
    ]
