# Generated by Django 6.0.2 on 2026-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='annee_academique',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
    ]
