# Generated by Django 6.0.2 on 2026-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_tp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note TP sur 20 (si applicable)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_cc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note CC sur 20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_rattrapage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note Rattrapage sur 20 (facultatif)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_sn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note SN sur 20', max_digits=5, null=True),
        ),
    ]
