# Generated by Django 5.2.8 on 2026-07-26 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0016_preinscription_date_naissance_preinscriptiondocument'),
        ('etudiants', '0004_etudiant_nom_parent_etudiant_whatsapp_parent'),
        ('modules', '0004_releve_notes_fields'),
        ('notes', '0004_backfill_note_annee_academique_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_cc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note CC sur 20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_rattrapage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note Rattrapage sur 20 (facultatif)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_sn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note SN sur 20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('etudiant', 'module', 'classe', 'evaluation', 'session'), name='unique_note_per_student_module_classe_eval_session'),
        ),
    ]
