# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='paie/justificatifs/')),
                ('beneficiaire_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
