# Generated by Django 5.2.8 on 2025-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=255)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
