# Generated by Django 5.2.8 on 2025-12-24 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='noms',
        ),
        migrations.AddField(
            model_name='paie',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paie',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paie',
            name='statut',
            field=models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente')], default='En attente', max_length=20),
        ),
    ]
