# Generated by Django 4.2.30 on 2026-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_de_paie', models.PositiveIntegerField(default=25, help_text='Jour du mois pour la paie (1-31)')),
            ],
            options={
                'verbose_name': 'Paramètres de Paie',
                'verbose_name_plural': 'Paramètres de Paie',
            },
        ),
    ]
