# Generated by Django 5.2.8 on 2026-06-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paie', '0002_parametrespaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrespaie',
            name='taux_cnps_employe',
            field=models.DecimalField(decimal_places=2, default=4.2, help_text='Taux CNPS employé (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='taux_cnps_employeur',
            field=models.DecimalField(decimal_places=2, default=16.67, help_text='Taux CNPS employeur (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='taux_irpp',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux IRPP par défaut (%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_object_id', models.PositiveIntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_echeances', models.PositiveIntegerField(default=1, help_text='Nombre de mois pour rembourser')),
                ('montant_echeance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motif', models.TextField(blank=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_debut_remboursement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de remboursement'), ('remboursee', 'Remboursée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('beneficiaire_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaire',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='CampagnePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_primes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nombre_bulletins', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campagne de paie',
                'verbose_name_plural': 'Campagnes de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_object_id', models.PositiveIntegerField()),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_primes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detail_primes', models.JSONField(blank=True, default=list)),
                ('detail_retenues', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('genere', 'Généré'), ('valide', 'Validé'), ('paye', 'Payé'), ('annule', 'Annulé')], default='genere', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('beneficiaire_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.campagnepaie')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois', 'beneficiaire_object_id'],
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_object_id', models.PositiveIntegerField()),
                ('type_prime', models.CharField(choices=[('transport', 'Prime de transport'), ('logement', 'Prime de logement'), ('rendement', 'Prime de rendement'), ('anciennete', "Prime d'ancienneté"), ('responsabilite', 'Prime de responsabilité'), ('risque', 'Prime de risque'), ('panier', 'Prime de panier'), ('heures_sup', 'Heures supplémentaires'), ('autre', 'Autre')], max_length=30)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_permanente', models.BooleanField(default=True, help_text='Appliquée chaque mois automatiquement')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('beneficiaire_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Prime / Indemnité',
                'verbose_name_plural': 'Primes / Indemnités',
                'ordering': ['-est_active', 'type_prime'],
            },
        ),
        migrations.CreateModel(
            name='Retenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_object_id', models.PositiveIntegerField()),
                ('type_retenue', models.CharField(choices=[('cnps', 'CNPS'), ('irpp', 'IRPP'), ('avance', 'Remboursement avance'), ('absence', 'Retenue pour absence'), ('pret', 'Remboursement prêt'), ('autre', 'Autre')], max_length=30)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_permanente', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('beneficiaire_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Retenue',
                'verbose_name_plural': 'Retenues',
                'ordering': ['-est_active', 'type_retenue'],
            },
        ),
    ]
