# Generated by Django 5.2.8 on 2026-01-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paie', '0002_remove_paie_noms_paie_date_paie_nom_paie_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='nom',
        ),
        migrations.AddField(
            model_name='paie',
            name='beneficiaire_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paie',
            name='beneficiaire_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
