# Generated by Django 5.2.8 on 2026-01-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_remove_paie_nom_paie_beneficiaire_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paie',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
