# Generated by Django 5.2.8 on 2026-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_parametrespaie_taux_cnps_employe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_travaillees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
