# Generated by Django 5.2.8 on 2026-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_add_heures_travaillees_to_bulletin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campagnepaie',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campagnepaie',
            name='type_beneficiaire',
            field=models.CharField(choices=[('tous', 'Tous'), ('personnel', 'Personnel'), ('formateur', 'Formateur')], default='tous', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='campagnepaie',
            constraint=models.UniqueConstraint(fields=('mois', 'annee', 'type_beneficiaire'), name='unique_campagne_per_month_type'),
        ),
    ]
