# Generated by Django 5.2.8 on 2026-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_alter_paie_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='paie/justificatifs/'),
        ),
    ]
