# Generated by Django 5.2.8 on 2026-08-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnels', '0002_personnel_date_embauche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date', models.DateField()),
                ('preuve', models.FileField(blank=True, null=True, upload_to='absences/preuves/', verbose_name='Preuve (PDF ou image)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='personnels.personnel')),
            ],
            options={
                'ordering': ['-date', '-date_demande'],
            },
        ),
    ]
