# Generated by Django 5.2.8 on 2026-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('Inscription', "Frais d'inscription"), ('Examen', "Frais d'examen"), ('Subvention', 'Subvention / Don'), ('Activite', 'Activité extrascolaire'), ('Location', "Location d'infrastructure"), ('Vente', 'Vente de produits/services'), ('Autres', 'Autres revenus')], max_length=20)),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('Validé', 'Validé'), ('En attente', 'En attente'), ('Rejeté', 'Rejeté')], default='Validé', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertePaiement',
        ),
    ]
