# Generated by Django 5.2.8 on 2026-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenus', '0002_revenu_delete_alertepaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenu',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='revenus/justificatifs/'),
        ),
    ]
