# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('fonction', models.CharField(choices=[('responsableRh', 'Responsable RH'), ('responsablePedagogique', 'Responsable Pédagogique'), ('responsableLogistique', 'Responsable Logistique'), ('stagiaire', 'Stagiaire'), ('femmeMenage', 'Femme de ménage'), ('responsableMarketing', 'Responsable Marketing')], default='stagiaire', max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
