# Generated by Django 4.2.30 on 2026-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='solde_conges_initial',
            field=models.PositiveIntegerField(default=0, verbose_name='Solde de congés annuel'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='solde_conges_restant',
            field=models.PositiveIntegerField(default=0, verbose_name='Solde de congés restant'),
        ),
    ]
