# Generated by Django 5.2.8 on 2026-01-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_personnel_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
