# Generated by Django 5.2.8 on 2026-01-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_personnel_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(choices=[('responsableRh', 'Responsable RH'), ('responsablePedagogique', 'Responsable Pédagogique'), ('responsableLogistique', 'Responsable Logistique'), ('stagiaire', 'Stagiaire'), ('femmeMenage', 'Femme de ménage'), ('responsableMarketing', 'Responsable Marketing')], default='stagiaire', max_length=50),
        ),
    ]
