# Generated by Django 5.2.8 on 2026-06-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('objet', models.CharField(help_text='Objet de la demande', max_length=200)),
                ('motif', models.TextField(blank=True, default='', help_text='Justification de la demande')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('en_cours', 'En cours de traitement'), ('approuvee', 'Approuvée'), ('livree', 'Livrée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('demandeur_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approbateur_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('commentaire_refus', models.TextField(blank=True, default='')),
                ('approbateur_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to='contenttypes.contenttype')),
                ('demandeur_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_articles', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField(default=1)),
                ('quantite_accordee', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaires.article')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='demandes.demandearticle')),
            ],
            options={
                'unique_together': {('demande', 'article')},
            },
        ),
    ]
