# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaires', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Refusée', 'Refusée'), ('Terminée', 'Terminée')], default='En attente', max_length=20)),
                ('demandeur_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaires.inventaire')),
                ('demandeur_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
