# Generated by Django 5.2.8 on 2025-12-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaires', '0006_inventaire_statut_alter_inventaire_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('demandeur', models.CharField(max_length=128)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Refusée', 'Refusée'), ('Terminée', 'Terminée')], default='En attente', max_length=16)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='inventaires.inventaire')),
            ],
        ),
    ]
