# Generated by Django 5.2.8 on 2026-01-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('Formateur', 'Formateur'), ('Personnel', 'Personnel')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='demandearticle',
            name='reference',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='demandearticle',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='demandes.users'),
        ),
    ]
