# Generated by Django 5.2.8 on 2026-01-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('demandes', '0002_users_alter_demandearticle_reference_and_more'),
        ('inventaires', '0009_alter_inventaire_categorie_alter_inventaire_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandearticle',
            name='demandeur',
        ),
        migrations.AddField(
            model_name='demandearticle',
            name='demandeur_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='demandearticle',
            name='demandeur_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaires.inventaire'),
        ),
        migrations.AlterField(
            model_name='demandearticle',
            name='reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='demandearticle',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Refusée', 'Refusée'), ('Terminée', 'Terminée')], default='En attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
