# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('modules', '0001_initial'),
        ('formateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps_academique', to='academique.classe')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academique.filiere')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formateurs.formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academique.niveau')),
            ],
        ),
    ]
