# Generated by Django 6.0.2 on 2026-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploidutemps', '0001_initial'),
        ('formations', '0004_formation_nombre_niveaux_alter_formation_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.niveau'),
        ),
    ]
