# Generated by Django 4.2.30 on 2026-05-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_cycleglobal_heure_pause_debut_and_more'),
        ('emploidutemps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academique.filiere'),
        ),
    ]
