# Generated by Django 6.0.2 on 2026-04-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('emploidutemps', '0002_emploidutemps_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='academique.classe'),
        ),
    ]
