# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='protected_files/')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', help_text='Type MIME du fichier', max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
