# Generated by Django 5.2.8 on 2026-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('duree_heures', models.IntegerField(help_text='Durée de la formation en heures')),
                ('description', models.TextField()),
                ('modules', models.ManyToManyField(related_name='formations', to='modules.module')),
            ],
        ),
    ]
