# Generated by Django 5.2.8 on 2026-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='description',
        ),
        migrations.AddField(
            model_name='formation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la formation en FCFA', max_digits=10),
        ),
    ]
