# Generated by Django 5.2.8 on 2026-01-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_remove_formation_description_formation_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='duree_heures',
            new_name='duree_mois',
        ),
    ]
