# Generated by Django 6.0.2 on 2026-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_rename_duree_heures_formation_duree_mois'),
        ('modules', '0002_remove_module_formateur_module_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='nombre_niveaux',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de niveaux (ex: 3 pour Licence)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='formations', to='modules.module'),
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='formations.formation')),
                ('modules', models.ManyToManyField(blank=True, related_name='niveaux', to='modules.module')),
            ],
        ),
    ]
