# Generated by Django 6.0.2 on 2026-04-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('formations', '0004_formation_nombre_niveaux_alter_formation_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='academique.cycle'),
        ),
    ]
