# Generated by Django 5.2.8 on 2025-12-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
        ('personnels', '0002_personnel_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='personnels.personnel'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
