# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Pré-inscrit', 'Pré-inscrit'), ('Inscrit', 'Inscrit')], default='Pré-inscrit', max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='academique.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(help_text='Ex: 2024-2025', max_length=15)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_academique_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_academique', to='academique.anneeacademique')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_detail', to='academique.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etudiants.etudiant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academique.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='etudiants/documents/')),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='etudiants.etudiant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'classe', 'annee_academique_ref'), name='unique_inscription_per_student_class_year_new'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'niveau', 'annee_academique')},
        ),
    ]
