# Generated by Django 5.2.8 on 2026-01-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='etudiants/documents/')),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='etudiants.etudiant')),
            ],
        ),
    ]
