# Generated by Django 4.2.30 on 2026-05-07 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_etudiant_initial_password_etudiant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('Avertissement', 'Avertissement'), ('Blâme', 'Blâme'), ('Exclusion temporaire', 'Exclusion temporaire'), ('Exclusion définitive', 'Exclusion définitive')], max_length=50)),
                ('motif', models.TextField()),
                ('date_sanction', models.DateField(default=django.utils.timezone.now)),
                ('duree', models.CharField(blank=True, help_text='Ex: 3 jours', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='etudiants.etudiant')),
            ],
        ),
    ]
