# Generated by Django 5.2.8 on 2026-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_etudiantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='EtudiantDocument',
        ),
    ]
