# Generated by Django 4.2.30 on 2026-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_sanctiondisciplinaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du parent'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='whatsapp_parent',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp du parent'),
        ),
    ]
