# Generated by Django 6.0.2 on 2026-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_remove_etudiant_documents_etudiantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
