# Generated by Django 6.0.2 on 2026-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_inscription'),
        ('formations', '0004_formation_nombre_niveaux_alter_formation_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.niveau'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'niveau', 'annee_academique')},
        ),
    ]
