# Generated by Django 6.0.2 on 2026-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_inscription_niveau_alter_inscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('Pré-inscrit', 'Pré-inscrit'), ('Inscrit', 'Inscrit')], default='Pré-inscrit', max_length=20),
        ),
    ]
