# Generated by Django 6.0.2 on 2026-04-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('etudiants', '0008_etudiant_statut'),
        ('formations', '0005_niveau_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='annee_academique_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='academique.anneeacademique'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='academique.classe'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'classe', 'annee_academique_ref'), name='unique_inscription_per_student_class_year'),
        ),
    ]
