# Generated by Django 6.0.2 on 2026-04-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateurs', '0004_formateur_salaire'),
        ('formations', '0004_formation_nombre_niveaux_alter_formation_modules_and_more'),
        ('modules', '0003_module_coefficient_module_has_tp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(help_text='Ex: 2024-2025', max_length=9, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.anneeacademique')),
                ('modules', models.ManyToManyField(blank=True, related_name='classes', to='modules.module')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='formations.niveau')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.cycle')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='academique.faculte')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academique.domaine')),
                ('formation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_filiere', to='formations.formation')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academique.anneeacademique')),
            ],
            options={
                'ordering': ['annee_academique__libelle', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evaluation', models.CharField(choices=[('CC', 'CC'), ('EXAMEN', 'Examen'), ('TP', 'TP'), ('RATTRAPAGE', 'Rattrapage'), ('AUTRE', 'Autre')], max_length=20)),
                ('libelle', models.CharField(max_length=150)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('date_evaluation', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academique.classe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='modules.module')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='academique.semestre')),
            ],
            options={
                'ordering': ['-date_evaluation', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='academique.filiere')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academique.specialite'),
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.specialite'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='formateurs.formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='modules.module')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='academique.classe')),
            ],
            options={
                'ordering': ['classe__nom', 'module__nom'],
                'constraints': [models.UniqueConstraint(fields=('enseignant', 'module', 'classe'), name='unique_affectation')],
            },
        ),
        migrations.AddConstraint(
            model_name='domaine',
            constraint=models.UniqueConstraint(fields=('faculte', 'nom'), name='unique_domaine_per_faculte'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(fields=('domaine', 'nom'), name='unique_filiere_per_domaine'),
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.UniqueConstraint(fields=('annee_academique', 'ordre'), name='unique_semestre_per_year_order'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('classe', 'module', 'type_evaluation', 'libelle'), name='unique_evaluation_signature'),
        ),
        migrations.AddConstraint(
            model_name='specialite',
            constraint=models.UniqueConstraint(fields=('filiere', 'nom'), name='unique_specialite_per_filiere'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('specialite', 'nom'), name='unique_cycle_per_specialite'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['specialite', 'niveau', 'annee_academique'], name='classe_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('specialite', 'niveau', 'annee_academique'), name='unique_classe_per_specialite_niveau_annee'),
        ),
    ]
