# Generated by Django 4.2.30 on 2026-04-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('formateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('libelle', models.CharField(help_text='Ex: 2024-2025', max_length=15, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_academique', to='academique.anneeacademique')),
            ],
            options={
                'ordering': ['annee_academique__libelle', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['filiere__nom', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['universite_tutelle__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academique.departement')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['departement__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academique.cycle')),
                ('modules', models.ManyToManyField(blank=True, related_name='niveaux_academique', to='modules.module')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['cycle__nom', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='UniversiteTutelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Université de Tutelle',
                'verbose_name_plural': 'Universités de Tutelle',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres_academique', to='academique.anneeacademique')),
            ],
            options={
                'ordering': ['annee_academique__libelle', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom_candidat', models.CharField(max_length=150)),
                ('prenom_candidat', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('bulletin', models.FileField(blank=True, null=True, upload_to='pre_inscriptions/bulletins/')),
                ('message', models.TextField(blank=True)),
                ('cycle_souhaite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.cycle')),
                ('filiere_souhaitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.filiere')),
                ('niveau_souhaite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.niveau')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type_evaluation', models.CharField(choices=[('CC', 'CC'), ('EXAMEN', 'Examen'), ('TP', 'TP'), ('RATTRAPAGE', 'Rattrapage'), ('AUTRE', 'Autre')], max_length=20)),
                ('libelle', models.CharField(max_length=150)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('date_evaluation', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_academique', to='academique.classe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_academique', to='modules.module')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_academique', to='academique.semestre')),
            ],
            options={
                'ordering': ['-date_evaluation', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='universite_tutelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academique.universitetutelle'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academique.filiere'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='academique.cycle')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='academique.filiere')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='modules.module')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='academique.niveau')),
            ],
            options={
                'verbose_name': 'Attribution de Cours',
                'verbose_name_plural': 'Attributions de Cours',
                'ordering': ['filiere__nom', 'cycle__ordre', 'niveau__nom', 'module__nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academique.cycle'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='classes_academique', to='modules.module'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academique.niveau'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_academique', to='academique.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_academique', to='formateurs.formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_academique', to='modules.module')),
            ],
            options={
                'ordering': ['classe__nom', 'module__nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.UniqueConstraint(fields=('annee_academique', 'ordre'), name='unique_semestre_per_year_order_new'),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('cycle', 'nom'), name='unique_niveau_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(fields=('departement', 'nom'), name='unique_filiere_per_departement'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('classe', 'module', 'type_evaluation', 'libelle'), name='unique_evaluation_signature_academique'),
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('universite_tutelle', 'nom'), name='unique_departement_per_universite'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('filiere', 'nom'), name='unique_cycle_per_filiere'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('filiere', 'cycle', 'niveau', 'module'), name='unique_course_assignment_per_path'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('filiere', 'niveau', 'annee_academique'), name='unique_classe_per_filiere_niveau_annee'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(fields=('enseignant', 'module', 'classe'), name='unique_affectation_academique'),
        ),
    ]
