# Generated by Django 4.2.30 on 2026-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresGlobaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pourcentage_cc', models.PositiveIntegerField(default=30, help_text='Pourcentage de la note CC (0-100)')),
                ('pourcentage_sn', models.PositiveIntegerField(default=70, help_text='Pourcentage de la note SN (0-100)')),
            ],
            options={
                'verbose_name': 'Paramètre Global',
                'verbose_name_plural': 'Paramètres Globaux',
            },
        ),
    ]
