# Generated by Django 4.2.30 on 2026-05-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_parametresglobaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(help_text='Ex: BTS, Licence, Master', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Cycle Global',
                'verbose_name_plural': 'Cycles Globaux',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cycle',
            name='unique_cycle_per_filiere',
        ),
        migrations.AlterField(
            model_name='cycle',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cycle',
            name='type_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles_acad', to='academique.cycleglobal'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('filiere', 'type_cycle'), name='unique_cycle_type_per_filiere'),
        ),
    ]
