# Generated by Django 6.0.2 on 2026-04-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_seed_academic_hierarchy'),
        ('formations', '0005_niveau_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_candidat', models.CharField(max_length=150)),
                ('prenom_candidat', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('bulletin', models.FileField(blank=True, null=True, upload_to='pre_inscriptions/bulletins/')),
                ('message', models.TextField(blank=True)),
                ('filiere_souhaitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.filiere')),
                ('niveau_souhaite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='formations.niveau')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
