# Generated by Django 6.0.2 on 2026-04-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_preinscription'),
        ('formations', '0005_niveau_cycle'),
        ('modules', '0003_module_coefficient_module_has_tp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['annee_academique__libelle', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['specialite__nom', 'ordre', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='domaine',
            options={'ordering': ['faculte__nom', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['domaine__nom', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['filiere__nom', 'nom']},
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cycle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='domaine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faculte',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='semestre',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='specialite',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academique.anneeacademique'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academique.cycle'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='formations.niveau'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='formation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_filiere', to='formations.formation'),
        ),
    ]
