# Generated by Django 4.2.30 on 2026-05-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_cycleglobal_remove_cycle_unique_cycle_per_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.cycle'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.niveau'),
        ),
    ]
