# Generated by Django 4.2.30 on 2026-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0004_alter_classe_cycle_alter_classe_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleglobal',
            name='heure_pause_debut',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='cycleglobal',
            name='heure_pause_fin',
            field=models.TimeField(default='13:00:00'),
        ),
    ]
