# Generated by Django 4.2.30 on 2026-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_cycleglobal_heure_pause_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleglobal',
            name='heure_debut_journee',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='cycleglobal',
            name='heure_fin_journee',
            field=models.TimeField(default='18:00:00'),
        ),
    ]
