# Generated by Django 4.2.30 on 2026-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0007_preinscription_nom_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(default='SmartCampus', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissement/logos/')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('couleur_primaire', models.CharField(default='#193A7F', max_length=20)),
                ('couleur_secondaire', models.CharField(default='#2A52A1', max_length=20)),
                ('typographie', models.CharField(default="'Inter', sans-serif", max_length=100)),
            ],
            options={
                'verbose_name': "Configuration de l'Établissement",
                'verbose_name_plural': "Configuration de l'Établissement",
            },
        ),
    ]
