# Generated by Django 4.2.30 on 2026-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0008_configurationetablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='couleur_texte',
            field=models.CharField(blank=True, default='#333333', max_length=20),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='nom_directeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='signature_directeur',
            field=models.ImageField(blank=True, null=True, upload_to='etablissement/signatures/'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='site_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='titre_directeur',
            field=models.CharField(blank=True, default='Le Directeur Général', max_length=255),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
