# Generated by Django 4.2.30 on 2026-05-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_has_tp_remove_module_pourcentage_cc_and_more'),
        ('academique', '0009_configurationetablissement_couleur_texte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=255)),
                ('type_epreuve', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('RATTRAPAGE', 'Rattrapage'), ('TP', 'TP'), ('AUTRE', 'Autre')], default='EXAMEN', max_length=20)),
                ('fichier', models.FileField(upload_to='epreuves/sujets/')),
                ('corrige', models.FileField(blank=True, help_text='Corrigé ou barème optionnel', null=True, upload_to='epreuves/corriges/')),
                ('auteur', models.CharField(blank=True, help_text="Nom de l'enseignant ou concepteur", max_length=150)),
                ('est_partage', models.BooleanField(default=True, help_text='Rendre visible par les étudiants')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='academique.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='academique.filiere')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='modules.module')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='academique.niveau')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='academique.semestre')),
            ],
            options={
                'ordering': ['-annee_academique__libelle', 'filiere__nom', 'niveau__nom', 'module__nom', 'nom'],
            },
        ),
    ]
