# Generated by Django 5.2.15 on 2026-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0010_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='responsable_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
