# Generated by Django 5.2.8 on 2026-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0013_backfill_preinscription_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='slogan',
            field=models.CharField(blank=True, default="Former aujourd'hui, construire demain.", max_length=255),
        ),
    ]
