# Generated by Django 5.2.8 on 2026-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0014_releve_notes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='logo_entete',
            field=models.ImageField(blank=True, help_text="Logo pour l'en-tête des documents (relevés, certificats)", null=True, upload_to='etablissement/logos/'),
        ),
    ]
